version: '3.8'

services:
  mysql-service:
    image: mysql:8.4
    container_name: mysql-cont
    environment:
      MYSQL_ROOT_PASSWORD: snowpoom
      MYSQL_DATABASE: wpdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: snowpoom1
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - net-wp
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 20s
      retries: 10
      start_period: 30s

  wordpress-service:
    image: wordpress:6
    container_name: wordpress-cont
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql-cont:3306
      WORDPRESS_DB_USER: admin 
      WORDPRESS_DB_PASSWORD: snowpoom1
      WORDPRESS_DB_NAME: wpdb
    volumes:
      - wordpress-vol:/var/www/html
    networks:
      - net-wp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 20s
      timeout: 20s
      retries: 10
      start_period: 50s
    restart: always
    depends_on:
      mysql-service:
        condition: service_healthy
volumes:
  mysql-data:
  wordpress-vol:

networks:
  net-wp:
    driver: bridge
